% demo_fetch_example.m
% OpenAlex cursor fetch demo (writes outputs to ./data)

close all; clc

thisFile = mfilename("fullpath");
repoRoot = fileparts(fileparts(thisFile)); % examples/ -> repo
addpath(fullfile(repoRoot, "src"));

outDir = fullfile(repoRoot, "data");
if ~isfolder(outDir), mkdir(outDir); end

maxRecords = 10000;
tag = "_" + string(maxRecords);
query = "MATLAB";

cursorMat = fullfile(outDir, "openalex_MATLAB_cursor_en" + tag + ".mat");
jsonlFile = fullfile(outDir, "openalex_MATLAB_cursor_en" + tag + ".jsonl");

demo_fetch(query, ...
  'perPage', 200, ...
  'maxRecords', maxRecords, ...
  'filter', "language:en", ...
  'outFile', cursorMat, ...
  'jsonlFile', jsonlFile, ...
  'keepInMemory', false, ...
  'saveEvery', 25, ...
  'saveEveryRecords', 5000, ...
  'pauseSec', 0.2, ...
  'verbose', true);
