% demo_fetch_example.m
% OpenAlex cursor fetch demo (writes outputs to ./data)

close all; clc

thisFile = mfilename("fullpath");
repoRoot = fileparts(fileparts(thisFile)); % examples/ -> repo
addpath(fullfile(repoRoot, "src"));

outDir = fullfile(repoRoot, "data");
if ~isfolder(outDir), mkdir(outDir); end

maxRecords = 10000;
tag = "_" + string(maxRecords);
query = "MATLAB";

cursorMat = fullfile(outDir, "openalex_MATLAB_cursor_en" + tag + ".mat");
jsonlFile = fullfile(outDir, "openalex_MATLAB_cursor_en" + tag + ".jsonl");

% Optional: polite pool contact (recommended)
% Set environment variable in your shell:
%   Windows (PowerShell):  $env:OPENALEX_MAILTO="you@example.com"
%   macOS/Linux (bash/zsh): export OPENALEX_MAILTO="you@example.com"
mailto = string(getenv("OPENALEX_MAILTO"));

openalex_fetch_works(query, ...
  'perPage', 200, ...
  'maxRecords', maxRecords, ...
  'filter', "language:en", ...
  'mailto', mailto, ...
  'outFile', cursorMat, ...
  'jsonlFile', jsonlFile, ...
  'keepInMemory', false, ...
  'saveEvery', 25, ...
  'saveEveryRecords', 1000, ...
  'progressEveryRecords', 1000, ...
  'pauseSec', 0.2, ...
  'verbose', true);