function results = openalex_read_jsonl(jsonlFile, varargin)
%OPENALEX_READ_JSONL  Read JSONL output generated by openalex_fetch_works
% One line = JSON array of OpenAlex Works (typically ~200 records)
%
% results = openalex_read_jsonl("openalex_MATLAB_cursor_en.jsonl");
% results = openalex_read_jsonl(..., 'maxRecords', 50000);

p = inputParser;
addRequired(p, 'jsonlFile', @(x) ischar(x) || isstring(x));
addParameter(p, 'maxRecords', inf, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'verbose', true, @(x) islogical(x) && isscalar(x));
parse(p, jsonlFile, varargin{:});
opt = p.Results;

jsonlFile  = string(opt.jsonlFile);
maxRecords = opt.maxRecords;
verbose    = opt.verbose;

fid = fopen(jsonlFile, 'r');
if fid < 0
    error("Cannot open file: %s", jsonlFile);
end
cleaner = onCleanup(@() fclose(fid));

chunks = cell(1024,1);  
nChunks = 0;
nTotal  = 0;

while true
    line = fgetl(fid);
    if ~ischar(line); break; end
    line = strtrim(line);
    if line == ""; continue; end

    % Each line contains a struct array (one API request)
    arr = jsondecode(line);

    nChunks = nChunks + 1;
    if nChunks > numel(chunks)
        chunks{end+1024,1} = [];
    end
    chunks{nChunks} = arr(:);

    nTotal = nTotal + numel(arr);

    if verbose && mod(nTotal, 10000) < 200
        fprintf("[read] loaded ~%d records...\n", nTotal);
    end

    if nTotal >= maxRecords
        break;
    end
end

chunks = chunks(1:nChunks);
results = vertcat(chunks{:});

% Trim to maxRecords if exceeded
if numel(results) > maxRecords
    results = results(1:maxRecords);
end
end
